# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 861, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.DetectionTab = QtWidgets.QWidget()
        self.DetectionTab.setObjectName("DetectionTab")
        self.ImportButton = QtWidgets.QPushButton(self.DetectionTab)
        self.ImportButton.setGeometry(QtCore.QRect(170, 310, 75, 23))
        self.ImportButton.setObjectName("ImportButton")
        self.DetectionButton = QtWidgets.QPushButton(self.DetectionTab)
        self.DetectionButton.setGeometry(QtCore.QRect(620, 310, 75, 23))
        self.DetectionButton.setObjectName("DetectionButton")
        self.Import = ImageView(self.DetectionTab)
        self.Import.setGeometry(QtCore.QRect(21, 20, 391, 271))
        self.Import.setObjectName("Import")
        self.Detection = ImageView(self.DetectionTab)
        self.Detection.setGeometry(QtCore.QRect(439, 20, 391, 271))
        self.Detection.setObjectName("Detection")
        self.tabWidget.addTab(self.DetectionTab, "")
        self.RecognitionTab = QtWidgets.QWidget()
        self.RecognitionTab.setObjectName("RecognitionTab")
        self.RecogintionButton = QtWidgets.QPushButton(self.RecognitionTab)
        self.RecogintionButton.setGeometry(QtCore.QRect(604, 310, 101, 23))
        self.RecogintionButton.setObjectName("RecogintionButton")
        self.Recognition = ImageView(self.RecognitionTab)
        self.Recognition.setGeometry(QtCore.QRect(439, 20, 391, 271))
        self.Recognition.setObjectName("Recognition")
        self.TestImageButton = QtWidgets.QPushButton(self.RecognitionTab)
        self.TestImageButton.setGeometry(QtCore.QRect(170, 310, 101, 23))
        self.TestImageButton.setObjectName("TestImageButton")
        self.TestImage = ImageView(self.RecognitionTab)
        self.TestImage.setGeometry(QtCore.QRect(21, 20, 391, 271))
        self.TestImage.setObjectName("TestImage")
        self.tabWidget.addTab(self.RecognitionTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

        self.Import.ui.histogram.hide()
        self.Import.ui.roiBtn.hide()
        self.Import.ui.menuBtn.hide()
        self.Import.ui.roiPlot.hide()
        self.Detection.ui.histogram.hide()
        self.Detection.ui.roiBtn.hide()
        self.Detection.ui.menuBtn.hide()
        self.Detection.ui.roiPlot.hide()
        self.TestImage.ui.histogram.hide()
        self.TestImage.ui.roiBtn.hide()
        self.TestImage.ui.menuBtn.hide()
        self.TestImage.ui.roiPlot.hide()
        self.Recognition.ui.histogram.hide()
        self.Recognition.ui.roiBtn.hide()
        self.Recognition.ui.menuBtn.hide()
        self.Recognition.ui.roiPlot.hide()

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition & Detection"))
        self.ImportButton.setText(_translate("MainWindow", "Import Image"))
        self.DetectionButton.setText(_translate("MainWindow", "Detect Face"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DetectionTab), _translate("MainWindow", "Face Detection"))
        self.RecogintionButton.setText(_translate("MainWindow", "Recognize Face"))
        self.TestImageButton.setText(_translate("MainWindow", "Import Test Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RecognitionTab), _translate("MainWindow", "Face Recognition"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
